
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showConfirmDialog;
import static javax.swing.JOptionPane.showMessageDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author black
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    String hamburguesas = "Hamburguesas seleccionadas: \n";
    String bebidas = "Bebidas seleccionadas: \n";
    String complementos = "Complementos seleccionados: \n";
    String nombre = "";
    int precio = 0;
    int h=0,c=0,b=0;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        redimensionar();
        deshabilitarBotones();
        deshabilitarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ticket = new javax.swing.JTabbedPane();
        pnlCombo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnWhopper = new javax.swing.JButton();
        btnWjr = new javax.swing.JButton();
        btnBacon = new javax.swing.JButton();
        btnLong = new javax.swing.JButton();
        btnCafe = new javax.swing.JButton();
        btnPepsi = new javax.swing.JButton();
        btnJugo = new javax.swing.JButton();
        btnAgua = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnGuardarNombre = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        pnlComplementos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnFran = new javax.swing.JButton();
        btnHash = new javax.swing.JButton();
        btnAros = new javax.swing.JButton();
        btnSupremas = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pnlTicket = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ePTicket = new javax.swing.JEditorPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mBtnCrear = new javax.swing.JMenuItem();
        mBtnConfirmar = new javax.swing.JMenuItem();
        mBtnTicket = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Elige tu hamburguesa preferida");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Elige tu bebida favorita");

        btnWhopper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWhopperActionPerformed(evt);
            }
        });

        btnWjr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWjrActionPerformed(evt);
            }
        });

        btnBacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaconActionPerformed(evt);
            }
        });

        btnLong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLongActionPerformed(evt);
            }
        });

        btnCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCafeActionPerformed(evt);
            }
        });

        btnPepsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPepsiActionPerformed(evt);
            }
        });

        btnJugo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugoActionPerformed(evt);
            }
        });

        btnAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAguaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Bacon king $78.00");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setText("Whopper $85.00");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setText("Long Jalapeño $50.00");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setText("Whopper JR $65.00");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setText("Jugo $25.00");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setText("Agua $15.00");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setText("Café $20.00");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setText("Pepsi $30.00");

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("Para poder agregar productos, tenemos primero que escribir nuestro nombre.");

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("Al momento de selecionar productos, podemos generar nuestro ticket.");

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("Daremos en generar click cuando seleccionemos todos lo que queramos comprar");

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("Y el ticket estara en la pestaña con el mismo nombre.");

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("Por ultimo en el menu seleccionaremos Pedido y confirmaremos el pedido.");

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("Si queremos cancelar el pedido seleccionaremos nuevo pedido.");

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel22.setText("Ingresa tu nombre.");

        txtNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        btnGuardarNombre.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnGuardarNombre.setText("Guardar");
        btnGuardarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarNombreActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("Tenemos que selecionar todos los productos que queramos de esta pestaña y de complementos.");

        javax.swing.GroupLayout pnlComboLayout = new javax.swing.GroupLayout(pnlCombo);
        pnlCombo.setLayout(pnlComboLayout);
        pnlComboLayout.setHorizontalGroup(
            pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComboLayout.createSequentialGroup()
                .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlComboLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(pnlComboLayout.createSequentialGroup()
                                .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnLong, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnWhopper, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlComboLayout.createSequentialGroup()
                                        .addGap(102, 102, 102)
                                        .addComponent(btnBacon, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlComboLayout.createSequentialGroup()
                                        .addGap(103, 103, 103)
                                        .addComponent(btnWjr, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(237, 237, 237)
                        .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel22)
                                .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlComboLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGuardarNombre)
                                .addGap(27, 27, 27))))
                    .addGroup(pnlComboLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlComboLayout.createSequentialGroup()
                        .addComponent(btnJugo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(btnAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlComboLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(62, 62, 62)
                        .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(btnPepsi, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))
                        .addContainerGap())))
            .addGroup(pnlComboLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlComboLayout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlComboLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlComboLayout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlComboLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlComboLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(314, 314, 314))))
            .addGroup(pnlComboLayout.createSequentialGroup()
                .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlComboLayout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel18))
                    .addGroup(pnlComboLayout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(jLabel19)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlComboLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlComboLayout.createSequentialGroup()
                        .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(184, 184, 184))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlComboLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(306, 306, 306))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlComboLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(333, 333, 333))))
            .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlComboLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabel5)
                    .addContainerGap(1121, Short.MAX_VALUE)))
        );
        pnlComboLayout.setVerticalGroup(
            pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComboLayout.createSequentialGroup()
                .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlComboLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnJugo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlComboLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnWhopper, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBacon, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(17, 17, 17)
                        .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlComboLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLong, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnWjr, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)))
                            .addGroup(pnlComboLayout.createSequentialGroup()
                                .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCafe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPepsi, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)))))
                    .addGroup(pnlComboLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarNombre)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addContainerGap())
            .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlComboLayout.createSequentialGroup()
                    .addGap(137, 137, 137)
                    .addComponent(jLabel5)
                    .addContainerGap(378, Short.MAX_VALUE)))
        );

        Ticket.addTab("Elige tu Combo", pnlCombo);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Elige complementos (opcional)");

        btnFran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFranActionPerformed(evt);
            }
        });

        btnHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHashActionPerformed(evt);
            }
        });

        btnAros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArosActionPerformed(evt);
            }
        });

        btnSupremas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupremasActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setText("Aros de cebolla $30.00");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel13.setText("Papas Hashbrown $30.00");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel14.setText("Papas a la francesa $30.00");

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel15.setText("Papas Supremas $30.00");

        javax.swing.GroupLayout pnlComplementosLayout = new javax.swing.GroupLayout(pnlComplementos);
        pnlComplementos.setLayout(pnlComplementosLayout);
        pnlComplementosLayout.setHorizontalGroup(
            pnlComplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlComplementosLayout.createSequentialGroup()
                .addGroup(pnlComplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlComplementosLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlComplementosLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addGroup(pnlComplementosLayout.createSequentialGroup()
                        .addGroup(pnlComplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlComplementosLayout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(btnFran, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHash, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlComplementosLayout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(btnSupremas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAros, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56)))
                .addGap(66, 66, 66))
            .addGroup(pnlComplementosLayout.createSequentialGroup()
                .addGroup(pnlComplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlComplementosLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel14))
                    .addGroup(pnlComplementosLayout.createSequentialGroup()
                        .addGap(502, 502, 502)
                        .addComponent(jLabel3)))
                .addContainerGap(504, Short.MAX_VALUE))
        );
        pnlComplementosLayout.setVerticalGroup(
            pnlComplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComplementosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addGroup(pnlComplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFran, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHash, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlComplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlComplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupremas, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlComplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel12))
                .addContainerGap(227, Short.MAX_VALUE))
        );

        Ticket.addTab("Agrega complementos", pnlComplementos);

        ePTicket.setEditable(false);
        jScrollPane1.setViewportView(ePTicket);

        javax.swing.GroupLayout pnlTicketLayout = new javax.swing.GroupLayout(pnlTicket);
        pnlTicket.setLayout(pnlTicketLayout);
        pnlTicketLayout.setHorizontalGroup(
            pnlTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1284, Short.MAX_VALUE)
        );
        pnlTicketLayout.setVerticalGroup(
            pnlTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );

        Ticket.addTab("Ticket", pnlTicket);

        jMenu1.setText("Compras");

        mBtnCrear.setText("Crear nueva compra");
        mBtnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBtnCrearActionPerformed(evt);
            }
        });
        jMenu1.add(mBtnCrear);

        mBtnConfirmar.setText("Confirmar compra");
        mBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBtnConfirmarActionPerformed(evt);
            }
        });
        jMenu1.add(mBtnConfirmar);

        jMenuBar1.add(jMenu1);

        mBtnTicket.setText("Generar Ticket");
        mBtnTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mBtnTicketMouseClicked(evt);
            }
        });
        jMenuBar1.add(mBtnTicket);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ticket)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ticket)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnWhopperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWhopperActionPerformed
        showMessageDialog(this, "Whopper agregada con exito.");
        hamburguesas+= "\nWhopper..........$85.00\n";
        precio +=85;
        habilitarBotones();
        h = 1;
    }//GEN-LAST:event_btnWhopperActionPerformed

    private void btnWjrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWjrActionPerformed
        showMessageDialog(this, "Whopper JR agregada con exito.");
        hamburguesas+= "\nWhopper JR.........$65.00\n";
        precio +=65;
        habilitarBotones();
        h = 1;
    }//GEN-LAST:event_btnWjrActionPerformed

    private void btnBaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaconActionPerformed
        showMessageDialog(this, "Bacon King agregada con exito.");
        hamburguesas+= "\nBacon King..........$78.00\n";
        precio +=78;
        habilitarBotones();
        h = 1;
    }//GEN-LAST:event_btnBaconActionPerformed

    private void btnLongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLongActionPerformed
        showMessageDialog(this, "Long Jalapeño agregada con exito.");
        hamburguesas+= "\nLong Jalapeño.........$50.00\n";
        precio +=50;
        habilitarBotones();
        h = 1;
    }//GEN-LAST:event_btnLongActionPerformed

    private void btnJugoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugoActionPerformed
        showMessageDialog(this, "Jugo agregada con exito.");
        bebidas+= "\nJugo.........$25.00\n";
        precio +=25;
        habilitarBotones();
        b = 1;
    }//GEN-LAST:event_btnJugoActionPerformed

    private void btnAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAguaActionPerformed
        showMessageDialog(this, "Agua agregada con exito.");
        bebidas+= "\nAgua.........$15.00\n";
        precio +=15;
        habilitarBotones();
        b = 1;
    }//GEN-LAST:event_btnAguaActionPerformed

    private void btnCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCafeActionPerformed
        showMessageDialog(this, "Café agregada con exito.");
        bebidas+= "\nCafé.........$20.00\n";
        precio +=20;
        habilitarBotones();
        b = 1;
    }//GEN-LAST:event_btnCafeActionPerformed

    private void btnPepsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPepsiActionPerformed
        showMessageDialog(this, "Pepsi agregada con exito.");
        bebidas+= "\nPepsi.........$30.00\n";
        precio +=30;
        habilitarBotones();
        b = 1;
    }//GEN-LAST:event_btnPepsiActionPerformed

    private void btnFranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFranActionPerformed
        showMessageDialog(this, "Papas a la francesa agregada con exito.");
        complementos+= "\nPapas a la francesa.........$30.00\n";
        precio +=30;
        habilitarBotones();
        c = 1;
    }//GEN-LAST:event_btnFranActionPerformed

    private void btnHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHashActionPerformed
        showMessageDialog(this, "Papas Hashbrown agregada con exito.");
        complementos+= "\nPapas Hashbrown.........$30.00\n";
        precio +=30;
        habilitarBotones();
        c = 1;
    }//GEN-LAST:event_btnHashActionPerformed

    private void btnSupremasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupremasActionPerformed
        showMessageDialog(this, "Papas supremas agregada con exito.");
        complementos+= "\nPapas supremas.........$30.00\n";
        precio +=30;
        habilitarBotones();
        c = 1;
    }//GEN-LAST:event_btnSupremasActionPerformed

    private void btnArosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArosActionPerformed
        showMessageDialog(this, "Aros de cebolla agregada con exito.");
        complementos+= "\nAros de cebolla.........$30.00\n";
        precio +=30;
        habilitarBotones();
        c = 1;
    }//GEN-LAST:event_btnArosActionPerformed

    private void mBtnTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mBtnTicketMouseClicked
        if(h!=1){
            hamburguesas = "";
        }
        if(b!=1){
            bebidas = "";
        }
        if(c!=1){
            complementos = "";
        }        
        generarTicket();
        mBtnTicket.setEnabled(false);
    }//GEN-LAST:event_mBtnTicketMouseClicked

    private void mBtnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBtnCrearActionPerformed
        if (showConfirmDialog(this, "¿Deseas eliminar la compra actual?", "Menu de Salida" ,JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION){
            limpiar();
        }
    }//GEN-LAST:event_mBtnCrearActionPerformed

    private void mBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBtnConfirmarActionPerformed
        if (showConfirmDialog(this, "¿Deseas completar la compra?", "Menu de Salida" ,JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION){
            showMessageDialog(this, "Compra realizada con exito.");
            limpiar();
        }
    }//GEN-LAST:event_mBtnConfirmarActionPerformed

    private void btnGuardarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarNombreActionPerformed
        if (txtNombre.getText().length() != 0){
           habilitarProductos();
           nombre+=txtNombre.getText();
           txtNombre.setEnabled(false);
        }else{
            showMessageDialog(this, "Tienes que agregar un nombre");
        }
        
    }//GEN-LAST:event_btnGuardarNombreActionPerformed
    public void habilitarProductos(){
        btnWhopper.setEnabled(true);
        btnFran.setEnabled(true);
        btnJugo.setEnabled(true);
        btnHash.setEnabled(true);
        btnBacon.setEnabled(true);
        btnLong.setEnabled(true);
        btnAros.setEnabled(true);
        btnSupremas.setEnabled(true);
        btnAgua.setEnabled(true);
        btnCafe.setEnabled(true);
        btnWjr.setEnabled(true);
        btnPepsi.setEnabled(true);
    }
    public void deshabilitarProductos(){
        btnWhopper.setEnabled(false);
        btnFran.setEnabled(false);
        btnJugo.setEnabled(false);
        btnHash.setEnabled(false);
        btnBacon.setEnabled(false);
        btnLong.setEnabled(false);
        btnAros.setEnabled(false);
        btnSupremas.setEnabled(false);
        btnAgua.setEnabled(false);
        btnCafe.setEnabled(false);
        btnWjr.setEnabled(false);
        btnPepsi.setEnabled(false);
    }
    public void habilitarBotones(){
        mBtnTicket.setEnabled(true);
        mBtnConfirmar.setEnabled(true);        
    }
    public void deshabilitarBotones(){
        mBtnTicket.setEnabled(false);
        mBtnConfirmar.setEnabled(false);
    }
    public void limpiar(){
        hamburguesas = "Hamburguesas seleccionadas: \n";
        bebidas = "Bebidas seleccionadas: \n";
        complementos = "Complementos seleccionados: \n";
        precio = 0;
        h=b=c=0;
        ePTicket.setText("");
        txtNombre.setText("");
        txtNombre.setEnabled(true);
        deshabilitarBotones();
        deshabilitarProductos();
    }
    public void generarTicket(){
        ePTicket.setContentType("text/html");
        ePTicket.setText("<HTML>"
                + "<HEAD>"
                + "<TITLE>Ticket de compra</TITLE>"
                + "</HEAD>"
                + "<BODY>"
                + "<CENTER><H1>Mi ticket de compra</H1></CENTER>"
                + "<P><CENTER><FONT SIZE=6 COLOR=\"red\">GRACIAS POR COMPRAR EN BURGUER KING!!!</FONT></CENTER>"
                +"<P><CENTER><FONT SIZE=6 COLOR=\"red\">Hola "+nombre+" aqui tienes tu pedido:</FONT></CENTER>"
                +"<P><CENTER><FONT SIZE=6 COLOR=\"blue\">"+hamburguesas+"</FONT></CENTER>"
                +"<P><CENTER><FONT SIZE=6 COLOR=\"blue\">"+bebidas+"</FONT></CENTER>"
                +"<P><CENTER><FONT SIZE=6 COLOR=\"blue\">"+complementos+"</FONT></CENTER>"
                +"<P><CENTER><FONT SIZE=6 COLOR=\"red\">El precio total de la compra es: "+precio+".00</FONT></CENTER>"
                +"<P><CENTER><FONT SIZE=6 COLOR=\"red\">Gracias por su preferencia!!</FONT></CENTER>"
                + "</HTML>");
    }
    /**
     * @param args the command line arguments
     */
    public void redimensionar(){
        //obtener imagenes
        ImageIcon wp = new ImageIcon(getClass().getResource("/imagenes/wp.png"));
        ImageIcon pf = new ImageIcon(getClass().getResource("/imagenes/pf.png"));
        ImageIcon jg = new ImageIcon(getClass().getResource("/imagenes/jg.png"));
        ImageIcon ph = new ImageIcon(getClass().getResource("/imagenes/ph.png"));
        ImageIcon bk = new ImageIcon(getClass().getResource("/imagenes/bk.png"));
        ImageIcon lj = new ImageIcon(getClass().getResource("/imagenes/lj.png"));
        ImageIcon ac = new ImageIcon(getClass().getResource("/imagenes/ac.png"));
        ImageIcon ps = new ImageIcon(getClass().getResource("/imagenes/ps.png"));
        ImageIcon ae = new ImageIcon(getClass().getResource("/imagenes/ae.png"));
        ImageIcon cf = new ImageIcon(getClass().getResource("/imagenes/cf.png"));
        ImageIcon wjr = new ImageIcon(getClass().getResource("/imagenes/wjr.png"));
        ImageIcon pp = new ImageIcon(getClass().getResource("/imagenes/pp.png"));
        //escalar imagenes
        Image wpe = wp.getImage().getScaledInstance(btnWhopper.getWidth(), btnWhopper.getHeight(), Image.SCALE_SMOOTH);
        Image pfe = pf.getImage().getScaledInstance(btnFran.getWidth(), btnFran.getHeight(), Image.SCALE_SMOOTH);
        Image jge = jg.getImage().getScaledInstance(btnJugo.getWidth(), btnJugo.getHeight(), Image.SCALE_SMOOTH);
        Image phe = ph.getImage().getScaledInstance(btnHash.getWidth(), btnHash.getHeight(), Image.SCALE_SMOOTH);
        Image bke = bk.getImage().getScaledInstance(btnBacon.getWidth(), btnBacon.getHeight(), Image.SCALE_SMOOTH);
        Image lje = lj.getImage().getScaledInstance(btnLong.getWidth(), btnLong.getHeight(), Image.SCALE_SMOOTH);
        Image ace = ac.getImage().getScaledInstance(btnAros.getWidth(), btnAros.getHeight(), Image.SCALE_SMOOTH);
        Image pse = ps.getImage().getScaledInstance(btnSupremas.getWidth(), btnSupremas.getHeight(), Image.SCALE_SMOOTH);
        Image aee = ae.getImage().getScaledInstance(btnAgua.getWidth(), btnAgua.getHeight(), Image.SCALE_SMOOTH);
        Image cfe = cf.getImage().getScaledInstance(btnCafe.getWidth(), btnCafe.getHeight(), Image.SCALE_SMOOTH);
        Image wjre = wjr.getImage().getScaledInstance(btnWjr.getWidth(), btnWjr.getHeight(), Image.SCALE_SMOOTH);
        Image ppe = pp.getImage().getScaledInstance(btnPepsi.getWidth(), btnPepsi.getHeight(), Image.SCALE_SMOOTH);
       //asignar imagenes
        Icon iwp  = new ImageIcon(wpe);
        Icon ipf  = new ImageIcon(pfe);
        Icon ijg  = new ImageIcon(jge);
        Icon iph  = new ImageIcon(phe);
        Icon ibk  = new ImageIcon(bke);
        Icon ilj  = new ImageIcon(lje);
        Icon iac  = new ImageIcon(ace);
        Icon ips  = new ImageIcon(pse);
        Icon iae  = new ImageIcon(aee);
        Icon icf  = new ImageIcon(cfe);
        Icon iwjr  = new ImageIcon(wjre);
        Icon ipp  = new ImageIcon(ppe);
        btnWhopper.setIcon(iwp);
        btnFran.setIcon(ipf);
        btnJugo.setIcon(ijg);
        btnHash.setIcon(iph);
        btnBacon.setIcon(ibk);
        btnLong.setIcon(ilj);
        btnAros.setIcon(iac);
        btnSupremas.setIcon(ips);
        btnAgua.setIcon(iae);
        btnCafe.setIcon(icf);
        btnWjr.setIcon(iwjr);
        btnPepsi.setIcon(ipp); 
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Ticket;
    private javax.swing.JButton btnAgua;
    private javax.swing.JButton btnAros;
    private javax.swing.JButton btnBacon;
    private javax.swing.JButton btnCafe;
    private javax.swing.JButton btnFran;
    private javax.swing.JButton btnGuardarNombre;
    private javax.swing.JButton btnHash;
    private javax.swing.JButton btnJugo;
    private javax.swing.JButton btnLong;
    private javax.swing.JButton btnPepsi;
    private javax.swing.JButton btnSupremas;
    private javax.swing.JButton btnWhopper;
    private javax.swing.JButton btnWjr;
    private javax.swing.JEditorPane ePTicket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mBtnConfirmar;
    private javax.swing.JMenuItem mBtnCrear;
    private javax.swing.JMenu mBtnTicket;
    private javax.swing.JPanel pnlCombo;
    private javax.swing.JPanel pnlComplementos;
    private javax.swing.JPanel pnlTicket;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
